import Footer from '@components/Layout/Footer/Footer'
import Navbar from '@components/Layout/Navbar/Navbar'
import '@styles/globals.css'

export const metadata = {
  title: 'Ineract Club Marsa Mind',
  description: 'Generated by create next app',
}

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}